
import streamlit as st
st.title("hello llm dev")
st.divider()
st.write("I am fine")
st.divider()
st.info("Hello lqr")
st.divider()
st.header("Hello everyone")
st.divider()
st.markdown("Hello **world**!")
st.divider()
st.subheader("This is a subheader")
st.badge("New")
st.caption("This is written small caption text")
st.divider()
st.code("a = 1234")
st.latex("\int a x^2 \,dx")
st.divider()
st.html("<p>Foo bar.</p>")
st.button("Reset", type="primary")
st.divider()
if st.button("Say hello"):
    st.write("Why hello there")
else:
    st.write("Goodbye")
st.divider()
