
import streamlit as st
st.title("hello llm dev")
st.divider()
st.write("I am fine")
st.divider()
st.info("Hello lqr")
st.divider()
st.header("Hello everyone")
st.divider()
st.divider()
st.markdown("Hello **world**!")
st.subheader("This is a subheader")
st.badge("New")
st.caption("This is written small caption text")
st.code("a = 1234")
st.latex("\int a x^2 \,dx")
st.html("<p>Foo bar.</p>")
